name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.4.0
  dio: ^5.3.3
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  #audio
  audioplayers: ^5.2.1
  #router
  cached_network_image: ^3.3.1
  go_router: ^14.2.7
  #picker
  image_picker: ^1.1.2
  universal_html: ^2.0.8
  web: ^1.1.0

  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9
  path: ^1.8.3
  permission_handler: ^11.3.0
  file_selector: 1.0.3
  flutter_riverpod: ^2.5.1
  just_audio: ^0.9.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Testing Dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.7
  mocktail: ^1.0.3
  integration_test: ^1.0.0
  patrol: ^3.6.1
  test: ^1.25.2
  fake_async: ^1.3.1
  network_image_mock: ^2.1.1

  # Riverpod Testing
  riverpod_test: ^2.0.0

  # Audio Testing
  just_audio_mock: ^0.1.0


  # Golden Tests
  golden_toolkit: ^0.15.0

  # Coverage
  coverage: ^1.7.2

flutter:
  uses-material-design: true
